### ISSUE TITLE
undefined reference to symbol 'pthread_getspecific@@GLIBC_2.4'

### ISSUE THREAD

**Issue by benoitguigal** [scheckmedia/CameraControllerApi#2]
Hello, 
when running "make" I get the error below:
g++ -g  -c -Wall -std=c++0x main.cpp -o main.o
g++ -g  -c -Wall -std=c++0x Api.cpp -o Api.o
Api.cpp: In member function ‘bool CameraControllerApi::Api::get_settings_by_key(std::string, CameraControllerApi::CCA_API_OUTPUT_TYPE, std::string&)’:
Api.cpp:70:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
g++ -g  -c -Wall -std=c++0x Base64.cpp -o Base64.o
g++ -g  -c -Wall -std=c++0x CameraController.cpp -o CameraController.o
CameraController.cpp: In member function ‘int CameraControllerApi::CameraController::_wait_and_handle_event(useconds_t, CameraEventType*, int)’:
CameraController.cpp:528:18: warning: variable ‘path’ set but not used [-Wunused-but-set-variable]
CameraController.cpp: In member function ‘void CameraControllerApi::CameraController::_set_capturetarget(int)’:
CameraController.cpp:570:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
g++ -g  -c -Wall -std=c++0x Command.cpp -o Command.o
g++ -g  -c -Wall -std=c++0x Helper.cpp -o Helper.o
g++ -g  -c -Wall -std=c++0x Server.cpp -o Server.o
g++ -g  -c -Wall -std=c++0x Settings.cpp -o Settings.o
g++ -g  -lboost_system -lgphoto2 -lmicrohttpd -lexif main.o Api.o Base64.o CameraController.o Command.o Helper.o Server.o Settings.o -o CameraControllerApi
/usr/bin/ld: CameraController.o: undefined reference to symbol 'pthread_getspecific@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: ld returned 1 exit status
Makefile:11: recipe for target 'CameraControllerApi' failed
make: *** [CameraControllerApi] Error 1

**Comment by condeDoug** [comment]
I'm having a similar issue.  Did you find a solution?

**Comment by condeDoug** [comment]
I figured it out.  Once you get to:
g++ -g -lboost_system -lgphoto2 -lmicrohttpd -lexif main.o Api.o Base64.o CameraController.o Command.o Helper.o Server.o Settings.o -o CameraControllerApi

add:   -lpthread

so use: 
g++ -g -lboost_system -lgphoto2 -lmicrohttpd -lexif -lpthread main.o Api.o Base64.o CameraController.o Command.o Helper.o Server.o Settings.o -o CameraControllerApi

**Comment by scheckmedia** [comment]
thanks, I've updated the Makefile
