### ISSUE TITLE
cca.json download initiating on web browser

### ISSUE THREAD

**Issue by WetBass** [scheckmedia/CameraControllerApi#4]
Hi,

When i "make" application and entering to http://myip:8888 my browser automatically downloads a file named cca.json

Contents of the file:

`{
    "cca_response":
    {
        "state": "fail",
        "message": "Invalid Command"
    }
}
`

Any idea? Thanks.

**Comment by scheckmedia** [comment]
yes, the problem ist that the root url ist not mapped. try the urls from the readme, eg.: http://myip:8888/settings?action=list

or call the minimal webif: http://myip:8888/webif/

hope I could help!

**Comment by WetBass** [comment]
Ohw.. by bad sorry :/ Thanks for quick return!
Best.
