### ISSUE TITLE
Makefile incompatibility

### ISSUE THREAD

**Issue by LakeIshikawa** [scheckmedia/CameraControllerApi#5]
I just realized that g++ linker options must be specified AFTER object files in my environment (Ubuntu 15.10) otherwise link errors will happen.

For compatibility, it might be better to swap $(OBJECTS) and $(LDFLAGS).

**Comment by scheckmedia** [comment]
I've changed the whole makefile. Now it creates a bin folder and copies the *.o files to this folder. can you try it whether it works on your ubuntu system?
