### ISSUE TITLE
Ubuntu 14.04 LTS make error

### ISSUE THREAD

**Issue by tpxtron** [scheckmedia/CameraControllerApi#6]
Hi,

when running make I get this output:
`g++ -g -lboost_system  -lgphoto2 -lmicrohttpd -lpthread -lexiv2 -o bin/CameraControllerApi obj/Api.o obj/Base64.o obj/CameraController.o obj/Command.o obj/Helper.o obj/main.o obj/Server.o obj/Settings.o
obj/CameraController.o: In function `CameraControllerApi::CameraController::release()':
/CameraControllerApi-master/src/CameraController.cpp:46: undefined reference to `gp_camera_exit'
obj/CameraController.o: In function `CameraControllerApi::CameraController::_init_camera()':
/CameraControllerApi-master/src/CameraController.cpp:85: undefined reference to `gp_camera_new'
/CameraControllerApi-master/src/CameraController.cpp:86: undefined reference to `gp_context_new'
/CameraControllerApi-master/src/CameraController.cpp:87: undefined reference to `gp_context_set_error_func'
/CameraControllerApi-master/src/CameraController.cpp:88: undefined reference to `gp_context_set_message_func'
/CameraControllerApi-master/src/CameraController.cpp:90: undefined reference to `gp_camera_init'
/CameraControllerApi-master/src/CameraController.cpp:92: undefined reference to `gp_camera_free'
obj/CameraController.o: In function `CameraControllerApi::CameraController::~CameraController()':
/CameraControllerApi-master/src/CameraController.cpp:100: undefined reference to `gp_camera_exit'
/CameraControllerApi-master/src/CameraController.cpp:101: undefined reference to `gp_context_unref'
obj/CameraController.o: In function `CameraControllerApi::CameraController::capture(char const*, std::string&)':
/CameraControllerApi-master/src/CameraController.cpp:130: undefined reference to `gp_camera_capture'
/CameraControllerApi-master/src/CameraController.cpp:136: undefined reference to `gp_file_new'
/CameraControllerApi-master/src/CameraController.cpp:139: undefined reference to `gp_file_new_from_fd'
/CameraControllerApi-master/src/CameraController.cpp:147: undefined reference to `gp_camera_file_get'
/CameraControllerApi-master/src/CameraController.cpp:157: undefined reference to `gp_camera_file_delete'
/CameraControllerApi-master/src/CameraController.cpp:172: undefined reference to `gp_camera_wait_for_event'
/CameraControllerApi-master/src/CameraController.cpp:185: undefined reference to `gp_file_free'
obj/CameraController.o: In function `CameraControllerApi::CameraController::preview(char const**)':
/CameraControllerApi-master/src/CameraController.cpp:198: undefined reference to `gp_file_new'
/CameraControllerApi-master/src/CameraController.cpp:204: undefined reference to `gp_camera_capture_preview'
/CameraControllerApi-master/src/CameraController.cpp:213: undefined reference to `gp_file_get_data_and_size'
/CameraControllerApi-master/src/CameraController.cpp:222: undefined reference to `gp_file_unref'
obj/CameraController.o: In function `CameraControllerApi::CameraController::get_file(char const*, char const*, std::string&)':
/CameraControllerApi-master/src/CameraController.cpp:270: undefined reference to `gp_file_new'
/CameraControllerApi-master/src/CameraController.cpp:276: undefined reference to `gp_camera_file_get'
obj/CameraController.o: In function `CameraControllerApi::CameraController::_get_files(boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> >&, char const*)':
/CameraControllerApi-master/src/CameraController.cpp:301: undefined reference to `gp_list_new'
/CameraControllerApi-master/src/CameraController.cpp:305: undefined reference to `gp_camera_folder_list_folders'
/CameraControllerApi-master/src/CameraController.cpp:309: undefined reference to `gp_list_count'
/CameraControllerApi-master/src/CameraController.cpp:313: undefined reference to `gp_list_get_name'
/CameraControllerApi-master/src/CameraController.cpp:324: undefined reference to `gp_list_new'
/CameraControllerApi-master/src/CameraController.cpp:328: undefined reference to `gp_camera_folder_list_files'
/CameraControllerApi-master/src/CameraController.cpp:332: undefined reference to `gp_list_count'
/CameraControllerApi-master/src/CameraController.cpp:342: undefined reference to `gp_list_get_name'
/CameraControllerApi-master/src/CameraController.cpp:358: undefined reference to `gp_file_new'
/CameraControllerApi-master/src/CameraController.cpp:363: undefined reference to `gp_camera_file_get'
/CameraControllerApi-master/src/CameraController.cpp:368: undefined reference to `gp_file_get_data_and_size'
/CameraControllerApi-master/src/CameraController.cpp:380: undefined reference to `gp_file_free'
/CameraControllerApi-master/src/CameraController.cpp:389: undefined reference to `gp_list_free'
/CameraControllerApi-master/src/CameraController.cpp:392: undefined reference to `gp_list_free'
obj/CameraController.o: In function `CameraControllerApi::CameraController::get_settings(boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> >&)':
/CameraControllerApi-master/src/CameraController.cpp:402: undefined reference to `gp_camera_get_config'
/CameraControllerApi-master/src/CameraController.cpp:408: undefined reference to `gp_widget_get_child_by_name'
obj/CameraController.o: In function `CameraControllerApi::CameraController::get_settings_choices(char const*, std::vector<std::string, std::allocator<std::string> >&)':
/CameraControllerApi-master/src/CameraController.cpp:424: undefined reference to `gp_camera_get_config'
/CameraControllerApi-master/src/CameraController.cpp:430: undefined reference to `gp_widget_get_child_by_name'
/CameraControllerApi-master/src/CameraController.cpp:436: undefined reference to `gp_widget_count_choices'
/CameraControllerApi-master/src/CameraController.cpp:439: undefined reference to `gp_widget_get_choice'
obj/CameraController.o: In function `CameraControllerApi::CameraController::get_settings_value(char const*, std::string&)':
/CameraControllerApi-master/src/CameraController.cpp:457: undefined reference to `gp_camera_get_config'
/CameraControllerApi-master/src/CameraController.cpp:463: undefined reference to `gp_widget_get_child_by_name'
/CameraControllerApi-master/src/CameraController.cpp:470: undefined reference to `gp_widget_get_value'
obj/CameraController.o: In function `CameraControllerApi::CameraController::set_settings_value(char const*, char const*)':
/CameraControllerApi-master/src/CameraController.cpp:486: undefined reference to `gp_camera_get_config'
/CameraControllerApi-master/src/CameraController.cpp:492: undefined reference to `gp_widget_get_child_by_name'
/CameraControllerApi-master/src/CameraController.cpp:498: undefined reference to `gp_widget_set_value'
/CameraControllerApi-master/src/CameraController.cpp:505: undefined reference to `gp_camera_set_config'
/CameraControllerApi-master/src/CameraController.cpp:510: undefined reference to `gp_widget_free'
obj/CameraController.o: In function `CameraControllerApi::CameraController::_wait_and_handle_event(unsigned int, CameraEventType*, int)':
/CameraControllerApi-master/src/CameraController.cpp:530: undefined reference to `gp_camera_wait_for_event'
obj/CameraController.o: In function `CameraControllerApi::CameraController::_read_widget(_CameraWidget*, boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> >&, std::string)':
/CameraControllerApi-master/src/CameraController.cpp:578: undefined reference to `gp_widget_get_name'
/CameraControllerApi-master/src/CameraController.cpp:581: undefined reference to `gp_widget_count_children'
/CameraControllerApi-master/src/CameraController.cpp:585: undefined reference to `gp_widget_get_child'
obj/CameraController.o: In function `CameraControllerApi::CameraController::_get_item_value(_CameraWidget*, boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> >&)':
/CameraControllerApi-master/src/CameraController.cpp:603: undefined reference to `gp_widget_get_id'
/CameraControllerApi-master/src/CameraController.cpp:604: undefined reference to `gp_widget_get_label'
/CameraControllerApi-master/src/CameraController.cpp:605: undefined reference to `gp_widget_get_name'
/CameraControllerApi-master/src/CameraController.cpp:606: undefined reference to `gp_widget_get_value'
/CameraControllerApi-master/src/CameraController.cpp:607: undefined reference to `gp_widget_get_type'
/CameraControllerApi-master/src/CameraController.cpp:612: undefined reference to `gp_widget_count_choices'
/CameraControllerApi-master/src/CameraController.cpp:617: undefined reference to `gp_widget_get_choice'
obj/CameraController.o: In function `CameraControllerApi::CameraController::_file_to_base64(_CameraFile*, std::string&)':
/CameraControllerApi-master/src/CameraController.cpp:660: undefined reference to `gp_file_get_data_and_size'
/CameraControllerApi-master/src/CameraController.cpp:665: undefined reference to `gp_file_get_mime_type'
obj/CameraController.o: In function `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:222: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:223: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:224: undefined reference to `boost::system::system_category()'
obj/CameraController.o: In function `boost::asio::error::get_system_category()':
/usr/include/boost/asio/error.hpp:216: undefined reference to `boost::system::system_category()'
obj/Helper.o: In function `CameraControllerApi::Helper::get_thumbnail_from_exif(char const*, unsigned long, std::string&, CameraControllerApi::Helper::ImageType)':
/CameraControllerApi-master/src/Helper.cpp:23: undefined reference to `Exiv2::ImageFactory::open(unsigned char const*, long)'
/CameraControllerApi-master/src/Helper.cpp:33: undefined reference to `Exiv2::PreviewManager::PreviewManager(Exiv2::Image const&)'
/CameraControllerApi-master/src/Helper.cpp:34: undefined reference to `Exiv2::PreviewManager::getPreviewProperties() const'
/CameraControllerApi-master/src/Helper.cpp:49: undefined reference to `Exiv2::PreviewManager::getPreviewImage(Exiv2::PreviewProperties const&) const'
/CameraControllerApi-master/src/Helper.cpp:50: undefined reference to `Exiv2::PreviewImage::size() const'
/CameraControllerApi-master/src/Helper.cpp:55: undefined reference to `Exiv2::PreviewImage::copy() const'
/CameraControllerApi-master/src/Helper.cpp:60: undefined reference to `Exiv2::DataBuf::release()'
/CameraControllerApi-master/src/Helper.cpp:49: undefined reference to `Exiv2::PreviewImage::~PreviewImage()'
/CameraControllerApi-master/src/Helper.cpp:49: undefined reference to `Exiv2::PreviewImage::~PreviewImage()'
obj/Helper.o: In function `Exiv2::DataBuf::operator Exiv2::DataBufRef()':
/usr/include/exiv2/types.hpp:246: undefined reference to `Exiv2::DataBuf::release()'
obj/Helper.o:(.rodata._ZTIN5Exiv210BasicErrorIcEE[_ZTIN5Exiv210BasicErrorIcEE]+0x10): undefined reference to `typeinfo for Exiv2::AnyError'
obj/main.o: In function `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:222: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:223: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:224: undefined reference to `boost::system::system_category()'
obj/Server.o: In function `CameraControllerApi::Server::run(int)':
/CameraControllerApi-master/src/Server.cpp:64: undefined reference to `pthread_create'
/CameraControllerApi-master/src/Server.cpp:68: undefined reference to `pthread_join'
obj/Server.o: In function `CameraControllerApi::Server::send_bad_response(MHD_Connection*)':
/CameraControllerApi-master/src/Server.cpp:98: undefined reference to `MHD_create_response_from_buffer'
/CameraControllerApi-master/src/Server.cpp:102: undefined reference to `MHD_queue_response'
/CameraControllerApi-master/src/Server.cpp:103: undefined reference to `MHD_destroy_response'
obj/Server.o: In function `CameraControllerApi::Server::send_auth_fail(MHD_Connection*)':
/CameraControllerApi-master/src/Server.cpp:115: undefined reference to `MHD_create_response_from_buffer'
/CameraControllerApi-master/src/Server.cpp:119: undefined reference to `MHD_queue_basic_auth_fail_response'
/CameraControllerApi-master/src/Server.cpp:120: undefined reference to `MHD_destroy_response'
obj/Server.o: In function `CameraControllerApi::Server::url_handler(void*, MHD_Connection*, char const*, char const*, char const*, char const*, unsigned long*, void**)':
/CameraControllerApi-master/src/Server.cpp:175: undefined reference to `MHD_basic_auth_get_username_password'
/CameraControllerApi-master/src/Server.cpp:182: undefined reference to `MHD_get_connection_values'
/CameraControllerApi-master/src/Server.cpp:191: undefined reference to `MHD_create_response_from_callback'
/CameraControllerApi-master/src/Server.cpp:192: undefined reference to `MHD_add_response_header'
/CameraControllerApi-master/src/Server.cpp:198: undefined reference to `MHD_queue_response'
/CameraControllerApi-master/src/Server.cpp:199: undefined reference to `MHD_destroy_response'
obj/Server.o: In function `CameraControllerApi::Server::handle_webif(void*, MHD_Connection*, char const*)':
/CameraControllerApi-master/src/Server.cpp:238: undefined reference to `MHD_create_response_from_fd'
/CameraControllerApi-master/src/Server.cpp:239: undefined reference to `MHD_add_response_header'
obj/Server.o: In function `CameraControllerApi::Server::handle_api(void*, char const*, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::string, void**)':
/CameraControllerApi-master/src/Server.cpp:296: undefined reference to `MHD_create_response_from_buffer'
/CameraControllerApi-master/src/Server.cpp:309: undefined reference to `MHD_add_response_header'
/CameraControllerApi-master/src/Server.cpp:312: undefined reference to `MHD_add_response_header'
/CameraControllerApi-master/src/Server.cpp:316: undefined reference to `MHD_add_response_header'
obj/Server.o: In function `CameraControllerApi::Server::http()':
/CameraControllerApi-master/src/Server.cpp:323: undefined reference to `MHD_start_daemon'
/CameraControllerApi-master/src/Server.cpp:333: undefined reference to `MHD_stop_daemon'
collect2: error: ld returned 1 exit status
make: *** [bin/CameraControllerApi] Error 1`

Got any ideas how to resolve this? I've installed all dependencies according to the readme and am a bit helpless now... :-(

**Comment by lux-foto** [comment]
Hi,
I have the same error.
Help me please run this app.

Error log:
`obj/CameraController.o: In function `CameraControllerApi::CameraController::release()':
/home/yuriy/server/CameraControllerApi/src/CameraController.cpp:46: undefined reference to `gp_camera_exit'
obj/CameraController.o: In function `CameraControllerApi::CameraController::_init_camera()':
/home/yuriy/server/CameraControllerApi/src/CameraController.cpp:85: undefined reference to `gp_camera_new'
/home/yuriy/server/CameraControllerApi/src/CameraController.cpp:86: undefined reference to `gp_context_new'
/home/yuriy/server/CameraControllerApi/src/CameraController.cpp:87: undefined reference to `gp_context_set_error_func'
/home/yuriy/server/CameraControllerApi/src/CameraController.cpp:88: undefined reference to `gp_context_set_message_func'
/home/yuriy/server/CameraControllerApi/src/CameraController.cpp:90: undefined reference to `gp_camera_init'
/home/yuriy/server/CameraControllerApi/src/CameraController.cpp:92: undefined reference to `gp_camera_free'`
and so on...

**Comment by scheckmedia** [comment]
Hi, which version of libgphoto2-dev have you installed?

**Comment by lux-foto** [comment]
@scheckmedia Thank you for your thought!
I updated gphoto2 and libgphoto2-dev to the latest version 2.5.10, but it did not change anything.
So, after a little help of my friend... It works!
Helped the extra announcement of the libraries **$(LDFLAGS)**:
`bin/$(EXECUTABLE): $(OBJ_FILES)`
`           $(CC) $(LDFLAGS) -o $@ $^ $(LDFLAGS)`

**Comment by scheckmedia** [comment]
cool, I've updated the file, thank you!
