### ISSUE TITLE
liveview problem

### ISSUE THREAD

**Issue by hjanuschka** [scheckmedia/CameraControllerApi#8]
hello

i want to display the liveview mpjpeg.
and do a capture.

but once a browser has liveview open - and streams (this works)
you cannot capture.

`/capture?action=shot`  returns.

```
{
    "cca_response": {
        "state": "fail",
        "message": "Not enough url parameter"
    }
}
```

@scheckmedia 

any idea where i can start looking into it?

regards

**Comment by hjanuschka** [comment]
ok i found out that the liveview, uses preview - wich locks the camera!
is there a way to get a single jpg - as preview?

**Comment by scheckmedia** [comment]
hi, did you tried the following sample code? 
https://github.com/scheckmedia/CameraControllerApi#live-view
This method creates a valid mjpeg-stream which will be rendered in you browser.

**Comment by hjanuschka** [comment]
yeah tried this. i do the image. but on a button i want to do a capture but capture does not work as long as the liveview is streaming - because camera is busy.


i am trying to patch in a /preview to get one single preview frame and later on doing the refresh every 500ms with javascript so a capture should work

--sent from mobile
